#!/bin/bash
#SBATCH --job-name=molmoact_finetune
#SBATCH --output=/home/lfeng/task_logs/%j.log
#SBATCH --partition=h100
#SBATCH --qos=vita
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=64
#SBATCH --gpus-per-node=4
#SBATCH --nodes=3
#SBATCH --time=24:00:00
#SBATCH --mem=200G

source /work/vita/lanfeng/conda_env/molmo/bin/activate

# Weights & Biases Configuration
export WANDB_PROJECT="molmoact-finetune"
export WANDB_ENTITY="" # Empty string defaults to your authenticated WandB profile

# Fetch the SLURM master node IP and assign it
nodes=( $( scontrol show hostnames $SLURM_JOB_NODELIST ) )
nodes_array=($nodes)
head_node=${nodes_array[0]}
head_node_ip=$(srun --nodes=1 --ntasks=1 -w "$head_node" hostname --ip-address)

echo Node IP: $head_node_ip

srun --nodes=1 --ntasks=1 -w "$head_node" python cache_model.py --repo-id allenai/MolmoAct-7B-D-0812

# Distribute the torchrun command natively referencing to the SLURM environment
srun --export=ALL,PYTHONPATH=$(pwd):$PYTHONPATH,OLMO_SHARED_FS=1 torchrun \
    --nnodes=3 \
    --nproc_per_node=4 \
    --rdzv_id=$SLURM_JOB_ID \
    --rdzv_backend=c10d \
    --rdzv_endpoint=$head_node_ip:29500 \
    launch_scripts/train_multitask_model.py \
    robot-finetune \
    allenai/MolmoAct-7B-D-0812 \
    --norm_stats_path /work/vita/lanfeng/vlas/wise_dataset_0.3.2_merged/dataset_statistics.json \
    --save_folder=checkpoints/wise_dataset_0_3_2_finetune \
    --save_overwrite \
    --duration 10000 \
    --ft_embedding all \
    --depth_tokens \
    --global_batch_size 24 \
    --lr_connector 5e-4 \
    --lr_vit 5e-4 \
    --lr_llm 5e-4 \
    --save_interval 2000 \
    --save_num_checkpoints_to_keep 5 \
    --max_images 2 \
    --lora_enable \
    --lora_rank 32 \
    --lora_alpha 16 \
    --lora_dropout 0.0 \
    --img_aug
